name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    
    - name: Install rye
      run: |
        curl -sSf https://rye.astral.sh/get | RYE_VERSION="0.4.0" RYE_INSTALL_OPTION="--yes" bash
        echo "$HOME/.rye/shims" >> $GITHUB_PATH
    
    - name: Install dependencies
      run: |
        rye sync
    
    - name: Run linter
      run: |
        rye lint
