name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Python Setup Rye
      uses: eifinger/setup-rye@v4.2.4
      with:
        enable-cache: true
    
    - name: Install dependencies
      run: |
        rye sync
    
    - name: Run linter
      run: |
        rye lint
