name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    
    - name: Install rye
      run: |
        pip install rye
        echo "$HOME/.rye/shims" >> $GITHUB_PATH
    
    - name: Install dependencies
      run: |
        rye sync
    
    - name: Run pytest
      run: |
        rye test

